#ifndef __ARLabStitcherwxMainFrame__
#define __ARLabStitcherwxMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "ARLabStitcherwx.h"

#include "base_wx/huginConfig.h"
#include "base_wx/wxPlatform.h"
#include "base_wx/platform.h"
#include <wx/wxprec.h>
#include<wx/dir.h>
#include<wx/process.h>

#include <hugin1/base_wx/MyExternalCmdExecDialog.h>
//// end generated include
using namespace std;
/** Implementing MainFrame */
class ARLabStitcherwxMainFrame : public MainFrame
{
public:
	/** Constructor */
	ARLabStitcherwxMainFrame( wxWindow* parent,wxString Dir );
	void newProcess(wxCommandEvent& WXUNUSED(event));
	void processcmd(wxCommandEvent& WXUNUSED(event));
	void ListBoxPicListClick(wxCommandEvent& e);
	void count_time(::wxTimerEvent& e);
	void end_process(::wxProcessEvent& e);
	void throw_to_parent(wxProcessEvent& e);




	void push_message(wxString message);
	int execexternal(wxString command,wxString tickmessage);
	
	//// end generated class members
private:

	

	MyExecPanel * m_execPanel;


	//std::string phasename;
	std::string sdir,gpsfileName ;
	wxString ExeDir,run_time;
	int time_count;
	int phase;
	std::string phasename[9];

	
	
	DECLARE_EVENT_TABLE()

public:
	void process(void);
};

enum
{
	ID_Quit,
	ID_About,
	//wxID_execPanel=900,

};


#endif // __ARLabStitcherwxMainFrame__
