#ifndef __ARLabStitcherwxControlPointFrame__
#define __ARLabStitcherwxControlPointFrame__

/**
@file
Subclass of ControlPointFrame, which is generated by wxFormBuilder.
*/

#include "ARLabStitcherwx.h"

//// end generated include

/** Implementing ControlPointFrame */
class ARLabStitcherwxControlPointFrame : public ControlPointFrame
{
	public:
		/** Constructor */
		ARLabStitcherwxControlPointFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __ARLabStitcherwxControlPointFrame__
