#ifndef __ARLabStitcherwxMainFrame__
#define __ARLabStitcherwxMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/


#include <vector>
#include <set>
#include <map>


#include "ARLabStitcherwx.h"

#include <appbase/ProgressDisplayOld.h>
#include <appbase/ProgressReporterOld.h>


#include "base_wx/huginConfig.h"
#include "base_wx/wxPlatform.h"
#include "base_wx/platform.h"
#include <wx/wxprec.h>
#include<wx/dir.h>
#include<wx/process.h>
#include<boost/lexical_cast.hpp>
#include <hugin1/base_wx/MyExternalCmdExecDialog.h>
#include<PT/Panorama.h>
#include "PT/utils.h"
#include <hugin_basic.h>
#include <hugin_utils/stl_utils.h>


//// end generated include
using namespace std;
/** Implementing MainFrame */

class GLPreviewFrame;
class ARLabStitcherwxMainFrame : public MainFrame
{
public:
	/** Constructor */
	ARLabStitcherwxMainFrame( wxWindow* parent,wxString Dir );
	void newProcess(wxCommandEvent& WXUNUSED(event));
	void processcmd(wxCommandEvent& WXUNUSED(event));
	void ListBoxPicListClick(wxCommandEvent& e);
	void count_time(::wxTimerEvent& e);
	void end_process(::wxProcessEvent& e);
	void throw_to_parent(wxProcessEvent& e);
	void change_status();



	void push_message(wxString message);
	int execexternal(wxString command,wxString tickmessage);

	GLPreviewFrame * getGLPreview();
	GLPreviewFrame * gl_preview_frame;

	//// end generated class members
private:

	int spin;

	MyExecPanel * m_execPanel;
	wxDateTime t;
	time_t time_start;
	time_t time_now;

	//std::string phasename;
	std::string sdir,gpsfileName,outfileName;
	wxString ExeDir,run_time;
	long time_count;
	int phase;
	std::string phasename[10];

	
	
	DECLARE_EVENT_TABLE()

public:
	void process(void);
};

enum
{
	ID_Quit,
	ID_About,
	//wxID_execPanel=900,

};


#endif // __ARLabStitcherwxMainFrame__
