#ifndef __ARLabStitcherwxControlPointFrame__
#define __ARLabStitcherwxControlPointFrame__

/**
@file
Subclass of ControlPointFrame, which is generated by wxFormBuilder.
*/

#include "ARLabStitcherwx.h"
#include "base_wx/huginConfig.h"
#include "base_wx/wxPlatform.h"
#include "base_wx/platform.h"
#include<boost/lexical_cast.hpp>
#include <hugin_basic.h>


//// end generated include
#include <iostream>
#include<vector>
//// end generated include
using namespace PT;
using namespace AppBase;
/** Implementing ControlPointFrame */
class ARLabStitcherwxControlPointFrame : public ControlPointFrame
{
public:
	/** Constructor */
	ARLabStitcherwxControlPointFrame(wxWindow* parent);
	void setPTO(wxString s);

private:
	wxString ptoFile;
	Panorama pano;
	//// end generated class members
	
public:
	int getReady();
	int UpdateDisplay();
};

#endif // __ARLabStitcherwxControlPointFrame__
